/**
 * The starter workbook offered for download, generated by `bun run template`
 * from the source workbook with the day grids stripped out.
 */
export const TEMPLATE_PATH = "/service-scheduler-template.xlsx";

/** Filename the browser saves it as, rather than the slug used in the URL. */
export const TEMPLATE_FILE_NAME = "Service Scheduler Template.xlsx";
